functions:
    usephp: false
    news: true
    ssl: true
ftp:
    user:
    password:
    host: test.example.com
    port: 21
    localRoot: ./dist/
    remoteRoot: ./path/to/web/root/
    include:
        - "*"
        - "**/*"
    deleteRemote: false