usephp: false
news: true
ssl: true
styleguide: true
sitemap: true
sitemap_xml: true
rss: true
ogp: true
analytics: true
searchconsole: true
pagetop: true
articlesns: true
themecolor: true
ios: true
chrome: true
fixedanchor_scss: true
lightbox: true
slick: true
svghexagon: false
imagemin: true
sitesearch: false
wordpress: false
advanced_typo: false
noscript: true