usephp: false
news: true
ssl: true
styleguide: true
sitemap: true
sitemap_xml: true
rss: true
ogp: true
analytics: true
searchconsole: true
pagetop: true
articlesns: true
themecolor: true
safari: true
ie: false
chrome: true
fixedanchor_scss: false
fixedanchor_js: true
lightbox: true
slick: true
svghexagon: false